### ISSUE TITLE
Arbitrary Contract Call

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#130]
## NFH-01M: Arbitrary Contract Call

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Input Sanitization](/appendix/finding-types#input-sanitization) | <span class="o-severity o-medium">Medium</span> | [NFTHolderCondition.sol:L110-L143](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/NFTHolderCondition.sol#L110-L143) |

### Description:

The `fulfill` function does not validate the `_contractAddress` argument and performs an external call to it via the `balanceOf` function.

### Example:

```solidity
function fulfill(
    bytes32 _agreementId,
    bytes32 _did,
    address _holderAddress,
    uint256 _amount,
    address _contractAddress
)
    external
    override
    returns (ConditionStoreLibrary.ConditionState)
{
    require(
        IERC1155Upgradeable(_contractAddress).balanceOf(_holderAddress, uint256(_did)) >= _amount,
        'The holder doesnt have enough NFT balance for the did given'
    );

    bytes32 _id = generateId(
        _agreementId,
        hashValues(_did, _holderAddress, _amount, _contractAddress)
    );
    ConditionStoreLibrary.ConditionState state = super.fulfill(
        _id,
        ConditionStoreLibrary.ConditionState.Fulfilled
    );

    emit Fulfilled(
        _agreementId,
        _did, 
        _holderAddress,
        _id,
        _amount
    );
    return state;
}
```

### Recommendation:

Although the Solidity version utilized by the system does not open up an attack vector, trusting the conformity of user-input smart contract addresses is a bad security practice and can lead to significant misbehaviours, such as a contract address behaving normally until after it has been accepted into the system. We advise the function to solely be available internally to avoid arbitrary contract input.

**Comment by mrsmkl** [comment]
I guess we could have some kind of whitelist for NFT contract?
