### ISSUE TITLE
Inexistent Validation of Condition Type

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#132]
## TNT-02M: Inexistent Validation of Condition Type

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Input Sanitization](/appendix/finding-types#input-sanitization) | <span class="o-severity o-minor">Minor</span> | [TransferNFT721Condition.sol:L119](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFT721Condition.sol#L119), [L121](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFT721Condition.sol#L121), [L122](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFT721Condition.sol#L122) |

### Description:

The `fulfill` function assumes the provided `_lockPaymentCondition` that is evaluated with regards to its fulfillment represents a lock payment condition which may not be the case.

### Example:

```solidity
address lockConditionTypeRef;
ConditionStoreLibrary.ConditionState lockConditionState;
(lockConditionTypeRef,lockConditionState,,,,,,) = conditionStoreManager
.getCondition(_lockPaymentCondition);
```

### Recommendation:

We advise the type reference address to be validated as being a lock payment type contract reference.

**Comment by mrsmkl** [comment]
I don't think it's assumed that it's a lock payment condition. When the agreement is executed, the lock payment id will be read from the agreement, so I don't think there's any possibility for mess up.
