### ISSUE TITLE
Inexistent Validation of Condition Type

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#135]
## TNF-03M: Inexistent Validation of Condition Type

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Input Sanitization](/appendix/finding-types#input-sanitization) | <span class="o-severity o-minor">Minor</span> | [TransferNFTCondition.sol:L174](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFTCondition.sol#L174), [L176](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFTCondition.sol#L176), [L237](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFTCondition.sol#L237), [L239](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFTCondition.sol#L239) |

### Description:

The `fulfill` functions assume the provided `_lockPaymentCondition` that is evaluated with regards to its fulfillment represents a lock payment condition which may not be the case.

### Example:

```solidity
address lockConditionTypeRef;
ConditionStoreLibrary.ConditionState lockConditionState;
(lockConditionTypeRef,lockConditionState,,,,,,) = conditionStoreManager
.getCondition(_lockPaymentCondition);
```

### Recommendation:

We advise the type reference address to be validated as being a lock payment type contract reference.

**Comment by mrsmkl** [comment]
Same as #132
