### ISSUE TITLE
Redundant Self-External Call

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#139]
## NFH-01C: Redundant Self-External Call

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [NFTHolderCondition.sol:L107](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/NFTHolderCondition.sol#L107), [L117](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/NFTHolderCondition.sol#L117) |

### Description:

The `this.fulfill` instruction performs a call to the `fulfill` function as if it was performed by an external party. This leads to the `msg.sender` being equivalent to the contract address.

### Example:

```solidity
function fulfill(
    bytes32 _agreementId,
    bytes32 _did,
    address _holderAddress,
    uint256 _amount
)
    external
    returns (ConditionStoreLibrary.ConditionState)
{
    return this.fulfill(_agreementId, _did, _holderAddress, _amount, address(nftRegistry));
}

function fulfill(
    bytes32 _agreementId,
    bytes32 _did,
    address _holderAddress,
    uint256 _amount,
    address _contractAddress
)
    external
    override
    returns (ConditionStoreLibrary.ConditionState)
{
```

### Recommendation:

We advise the `fulfill` function to be declared as `public` (or `internal` according to the other exhibit of the report) as it currently utilizes more gas than necessary for no reason.

**Comment by H34D** [comment]
fixed with #145
