### ISSUE TITLE
Unutilized Input Argument

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#142]
## TNT-02C: Unutilized Input Argument

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [TransferNFT721Condition.sol:L39](https://github.com/nevermined-io/contracts/blob/a8e380b1cfac24034b112ae3a5196c27b4c3afb8/contracts/conditions/NFTs/TransferNFT721Condition.sol#L39) |

### Description:

The `TransferNFT721Condition` has a redundant `address` argument declared in its `initialize` function.

### Example:

```solidity
function initialize(
    address _owner,
    address _conditionStoreManagerAddress,
    address _didRegistryAddress,
    address
)
    external
    override
    initializer()
{
```

### Recommendation:

We advise the argument to be omitted and a proper interface definition to be set for it as the redundant argument increases the gas cost of the contract call.

**Comment by mrsmkl** [comment]
Fixed in #145
