### ISSUE TITLE
bring back "yarn test" in default build

### ISSUE THREAD

**Issue by H34D** [nevermined-io/contracts#166]
because of some problems with the build the unit tests were split into separate calls:

https://github.com/nevermined-io/contracts/blob/14ccef9241a854d43cfbb32ab01053032f6a3f5c/.github/workflows/build.yml#L36-L40

it should be `yarn test:unit` again

@mrsmkl @eruizgar91

**Comment by mrsmkl** [comment]
should now be working after updating to hardhat
