### ISSUE TITLE
Polygon docker container generations fails in contracts

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#196]
The docker container for polygon is failing during the generation in Dockerhub:
https://hub.docker.com/repository/registry-1.docker.io/neverminedio/polygon-localnet/builds/1a67afe7-00f2-4206-b2f2-d9c93ca13724

**Comment by mrsmkl** [comment]
Looks like the node didn't start up in 5 seconds, perhaps there should be a loop to wait for the node...

**Comment by aaitor** [comment]
now works:
https://hub.docker.com/repository/registry-1.docker.io/neverminedio/polygon-localnet/builds/bff22e15-c035-4c5a-aa88-5d462206df65

thanks @mrsmkl
