### ISSUE TITLE
Generate an `arm64` docker image for contracts

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#251]
## Is your feature request related to a problem? Please describe.

Mac users want to run contracts in docker container

## Describe the solution you'd like

After a tag or push to master the contracts are packed in arm64 additional docker container. Because Docker Hub doesn't support this natively this is done via Github Actions workflow

## Additional context

For this to be useful, other docker images (metadata-api, gateway, etc.) need to have arm64 support too.

**Comment by r-marques** [comment]
This might help and it works entirely on dockerhub https://hub.docker.com/r/ckulka/multi-arch-example

**Comment by aaitor** [comment]
closed as not planned
