### ISSUE TITLE
Make the provider able to download and decrypt in DTP scenarios

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#407]
## Is your feature request related to a problem? Please describe.

The download function in regular `access` scenarios allows the owner or provider of the asset to download data. For some other scenarios is required to have the same solution for encrypted data. That would allow to data providers to `download` data encrypted via `DTP` and decrypt.

**Comment by mrsmkl** [comment]
Looks like this should be done in the node, it should have access to the encrypted password.
