### ISSUE TITLE
NFT1155 Subscription contract should allow batch operations

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#511]
`NFT1155SubscriptionUpgradeable` should support batch operations using the contract bespoke logic:

- [ ] mintBatch
- [ ] burnBatch
- [ ] balanceOfBatch

This should be a new version of the contracts `v3.5.3`? that need to be upgraded in `arbitrum-goerli`, currently `v3.5.2`

**Comment by r-marques** [comment]
https://github.com/dragonfly-xyz/useful-solidity-patterns/tree/main/patterns/eip712-signed-messages
