### ISSUE TITLE
Prevention of DID Registration

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#69]
## DID-02M: Prevention of DID Registration

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-medium">Medium</span> | [DIDFactory.sol:L238-L239](https://github.com/nevermined-io/contracts/blob/eb43dc4f438bf5e9450ba285570c8d12551467db/contracts/registry/DIDFactory.sol#L238-L239) |

### Description:

The `_wasGeneratedBy` provenance creation uses the `_did` as the ID of the provenance which, if consumed by another DID as part of another provenance ID, would render registration of the DID impossible.

### Example:

```solidity
function registerDID(
    bytes32 _did,
    bytes32 _checksum,
    address[] memory _providers,
    string memory _url,
    bytes32 _activityId,
    string memory _attributes
)
public
virtual
onlyValidAttributes(_attributes)
returns (uint size)
{
    require(
        didRegisterList.didRegisters[_did].owner == address(0x0) ||
        didRegisterList.didRegisters[_did].owner == msg.sender,
        'Only DID Owners'
    );

    uint updatedSize = didRegisterList.update(_did, _checksum, _url);

    // push providers to storage
    for (uint256 i = 0; i < _providers.length; i++) {
        didRegisterList.addProvider(
            _did,
            _providers[i]
        );
    }

    emit DIDAttributeRegistered(
        _did,
        didRegisterList.didRegisters[_did].owner,
        _checksum,
        _url,
        msg.sender,
        block.number
    );
    
    _wasGeneratedBy(
        _did, _did, msg.sender, _activityId, _attributes);
    
    return updatedSize;
}
```

### Recommendation:

We advise this provenance to also accept an input as to what provenance ID it should utilize to prevent misuse as well as race-conditions from occuring.

**Comment by mrsmkl** [comment]
One possibility would be to associate the provenance items with dids `mapping (bytes32 => mapping (bytes32 => Provenence))`, but this would change the interfaces...

**Comment by aaitor** [comment]
In this case the main intention of the `wasGeneratedBy` provenance event is to report a specific asset creation, that that only can happen once. Taking into account the `did` is an unique identifier in the assets registry, the usage of the `did` as `provId` is a design election, allowing only to the creation of an asset event to register a `provId` that is the `did`
