### ISSUE TITLE
Pull-Over-Push Pattern

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#70]
## DID-03M: Pull-Over-Push Pattern

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Input Sanitization](/appendix/finding-types#input-sanitization) | <span class="o-severity o-minor">Minor</span> | [DIDFactory.sol:L156-L158](https://github.com/nevermined-io/contracts/blob/eb43dc4f438bf5e9450ba285570c8d12551467db/contracts/registry/DIDFactory.sol#L156-L158) |

### Description:

The `setManager` function overwrites the previously set `manager` with the new one without validating it.

### Example:

```solidity
function setManager(address _addr) external onlyOwner {
    manager = _addr;
}
```

### Recommendation:

We advise the pull-over-push pattern to be applied whereby a new `manager` is first proposed and consequently needs to accept their position via another dedicated function ensuring that they are able to actuate transactions on the blockchain.

**Comment by mrsmkl** [comment]
I think that the manager will just be a contract, so there's no point in validating it further.
I'll just add a comment.
